[package]
name = "uniqr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }
rand = { workspace = true }
